# Never change this value
config-version: 1

# Toggles debug mode, which prints additional information when the plugin does something.
debug: false

# Login notification delay time (seconds)
delayTime: 600

# User login/logout notification
notification: false

# Login LoginNotificationTask tweet message
loginTweetMessage: |-
  [%DATE%]
  %PLAYER% joined Minecraft server.

# Logout LoginNotificationTask tweet message
logoutTweetMessage: |-
  [%DATE%]
  %PLAYER% left Minecraft server.

# Hash tag
hashTag:
  - TwipostMC
