# Never change this value
config-version: 1

# Toggles debug mode, which prints additional information when the plugin does something.
debug: false

# Login notification interval (minutes)
intervalTime: 15

# User login/logout notification
notification: false

# Login notification tweet message
loginTweetMessage: "%Player% joined Minecraft server."

# Logout notification tweet message
logoutTweetMessage: "%Player% left Minecraft server."