############################################################
# +------------------------------------------------------+ #
# |                       General                        | #
# +------------------------------------------------------+ #
############################################################

# Never change this value
config-version: 1

# Toggles debug mode, which prints additional information when the plugin does something.
debug: false

# Twitter API token
consumerKey: 'changeme'
consumerSecret: 'changeme'
accessToken: 'changeme'
accessTokenSecret: 'changeme'