# Never change this value
config-version: 1

# Toggles debug mode, which prints additional information when the plugin does something.
debug: false

# Login notification interval (minutes)
intervalTime: 0

# User login/logout notification
notification: false

# Login notification tweet message
loginTweetMessage: -|
  [%DATE%]
  %PLAYER% joined Minecraft server.

# Logout notification tweet message
logoutTweetMessage: -|
  [%DATE%]
  %PLAYER% left Minecraft server.

# Hash tag
hashTag:
  - TwipostMC
