############################################################
# +------------------------------------------------------+ #
# |                       General                        | #
# +------------------------------------------------------+ #
############################################################

# Never change this value
config-version: 1

# Toggles debug mode, which prints additional information when the plugin does something.
debug: false

# Twitter server's token
consumerKey: 'changeme'
consumerSecret: 'changeme'
accessToken: 'changeme'
accessTokenSecret: 'changeme'

# Login notification interval (minutes)
intervalTime: 15

# User login notification
loginNotification: true

# User Logout notification
logoutNotification: true

# Login notification tweet message
loginTweetMessage: "%Player% joined Minecraft server."

# Logout notification tweet message
logoutTweetMessage: "%Player% left Minecraft server."