name: TwipostMC
version: @version@
main: com.tklcraft.twipostmc.TwipostMCPlugin
api-version: 1.13
authors: [kanakiyo314, kakeru4127]

commands:
  tw:
    description: Controls TwipostMC.
    aliases: twipost
    usage: |
      /<command> subcommand - description...

permissions:
  tw.*:
    description: Give access to all TwipostMC functions
    default: false
    children:
      tw.sample: true
      tw.ping: true
      tw.post: true
      tw.debug: true
      tw.notification: true

  tw.register:
    description: Allows /tw register
    default: op

  tw.pin:
    descriptino: Allows /tw ping
    default: op

  tw.post:
    description: Allows /tw post
    default: op

  tw.debug:
    description: Allosws /tw debug
    default: op

  tw.notification:
    description: Allows /tw notification
    default: op